name: Generate Report

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Run install
        run: npm install

      - name: Run generator
        run: node --run generate
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/update pull request
        uses: gr2m/create-or-update-pull-request-action@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: >
            Here's the new weekly report for the expressjs, jshttp, and pillar.js organizations.
          branch: report
          commit-message: 'docs: generate weekly report'
          title: 'docs: generate weekly report'
          assignees: bjohansebas
          auto-merge: squash
